FROM docker.io/node:lts-bookworm

RUN \
	apt-get update && \
	apt-get install -y sudo git curl wget openssl ca-certificates openssh-client bash make

RUN \
	curl -fsSL https://get.docker.com | sh

RUN \
	mkdir -p /usr/local/lib/docker/cli-plugins && \
	curl -SL https://github.com/docker/compose/releases/download/v2.26.1/docker-compose-linux-x86_64 -o /usr/local/lib/docker/cli-plugins/docker-compose

ENTRYPOINT ["/bin/bash"]
