FROM ghcr.io/privacy-com/ci-images:debian

RUN \
	curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path && \
	mv /root/.cargo/bin/* /usr/local/bin
	

COPY ./rust/entrypoint.sh /entrypoint.sh
RUN chmod a+x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
