FROM ghcr.io/privacy-com/ci-images:alpine

RUN \
	apk add --no-cache rustup

RUN \
	rustup-init -y && mv /root/.cargo/bin/* /usr/local/bin


COPY ./rust/entrypoint.sh /entrypoint.sh
RUN chmod a+x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
CMD ["/bin/bash"]
